export default {
  name: 'owner2',
  alias: ['ownerinfo2', 'botinfo'],
  description: 'Show owner info with AI rich response',
  category: 'general',
  ownerOnly: false,

  async execute(sock, msg, args, prefix, options) {
    const sender = msg.key.remoteJid;

    await sock.relayMessage(
      sender,
      {
        botForwardedMessage: {
          message: {
            richResponseMessage: {
              messageType: "AI_RICH_RESPONSE_TYPE_STANDARD",
              submessages: [
                {
                  messageType: "AI_RICH_RESPONSE_TEXT",
                  messageText: "[ UNSUPPORTED_TYPE - MBPostPrimitive]"
                }
              ],
              unifiedResponse: {
                data: "AAAAAAAAAAAAAgUAAAAJAAAAAAYAAAAAAAAAAAACAAAAAAABAAAAAAAAAAUAAAEAAAAABQAAAAEAAAAAAAAAAQAAAAAAAAAAAAAAAAADAAAAAgUAAAAAAAAAAAIAAAADAAIBAAAAAAAAAAAHAAAAAAAAAQAAAAACAAAAAAAAAAcAAAAAAAAAAAAAAAAAAAAAAAMAAAAAAAAAAAAAAAAAAAAAAAEAAgAAAAAAAAAAAAYAAAAAAAAAAAAAAAAAAAkAAAAAAAADAAAAAwABAAAAAAAAAAAAAAAAAAAAAAAAAAYAAAkAAAAAAAAABQAAAAAAAAMAAAAACQAAAwAAAAAAAAAABQAAAAAAAAAAAAABCQIAAAAAAAAAAAAAAAYAAAABAAAAAAAAAAEAAAAAAAAAAAADAAAAAAAGAAAAAAAAAAAAAAgAAAAAAAAAAAAAAgAAAAAJBAAAAQAAAAkAAAAAAAAAAAAAAAAAAAAAAAAACQAAAAkAAAAAAAAACQAAAAAAAAAAAAAAAAAAAAAAAAAFBgAAAAAAAAADAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADAAAAAAAAAAABBQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAMAAAAACQAAAAAAAAMAAAAABQAAAAAAAAAAAAAAAAAAAwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAQAAAIAAAAAAAAAAgAAAAAAAAAAAAQAAgAAAAAAAAAAAAAAAAAEAAIAAAAAAAAAAAAAAAAAAAAAAAAAAQkAAAMAAAAAAAYAAAAFAAAAAAACAQAAAAUAAAEJAAADAAAAAAAGAAAAAAAAAAAAAAAAAAEJAAADAAAAAAAGAAAAAAAAAAAAAwAAAAAAAAAAAAAAAAAAAAAABgAACQMAAAUAAAAIAgAAAAEAAAAFAAAAAAAAAAAAAAAAAAAJAAAACQAAAAAAAAAAAAAAAAYAAAAAAAAAAAAACAAAAgAAAAAAAAAAAAQAAAAFAAAABQAAAAAAAAAAAAAAAAAAAAAAAAkAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAIJAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAIJAAAAAAAAAAAAAAAABgAAAAAAAAAAAAAIAAAAAAAAAAAAAAIAAAAACQQAAAEAAAAJAAAACAMAAAAAAAAAAAAAAAAAAAAAAAIAAAADAAAAAAAAAAAAAAAAAAAAAAkAAAAAAAAAAAAAAAkAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAkAAAAJAAAAAAAAAAAAAAAAAAAACAAAAAAAAAMABQAAAAAAAAEAAAAAAAAAAAAAAwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAGAAAAAAAAAAEAAAAAAAAAAAAAAAAAAAAAAAAAAAAABQAAAAAAAAAAAAAABQYAAAAAAAAAAAAAAAAAAAkAAAAAAAAAAAAAAwAAAAAABgAAAAAAAAAAAAAIAAAAAAAAAAAAAAIAAAAACQQAAAEAAAAJAAAACAMAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABAAAAAAAAAAkBAAAAAAAAAAAAAAAAAAAAAAACAAAAAAAAAAAAAAAAAAAAAAUAAAIAAAACCQAAAAAAAAAAAAAAAAAAAAAAAAMAAAACAAAAAAAAAAAABgAAAAAAAAQAAAAAAAAAAAAAAAAAAAAAAAAAAAQAAAABAAMAAAAAAAAAAwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAgAAAAAAAAAAAAAAAAkAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAIAAACAAAAAAAAAAAAAAAACQAAAAAAAAAEAAAACQAAAAAAAAAAAAACCAAAAgAAAAAJAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAIJAAAAAAAAAAAAAAAAAAAAAAAAAgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACCQEAAAAAAAAABQAAAAAAAgkAAAAAAAAAAAAAAgkBAAAAAAAAAAUAAAAAAAAAAAAAAAAAAgkBAAAAAAAAAAUAAAAAAAMAAAADAAAAAAAGAAAAAAAAAAAAAAgAAAIAAAAAAAAAAAAEAAAABQAAAAUAAAAAAAAAAAAAAAAAAwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAMAAAAAAQAAAAAAAAAABAAAAAAAAAAFAAAAAAAAAAAAAwAAAAIAAAAAAAAAAAAAAAAFAAAAAAAAAAAAAAAAAAAACQAAAAAAAAIAAAAAAAAAAAAAAAAAAAAACQAAAAAAAAIAAAACBAAAAAAAAAAAAAAAAAAAAgAAAAAAAAAAAAAAAAAAAAAFAAACAAAAAAAAAAIAAQAAAAAAAAAAAAAAAAACAAAAAAkBAAIAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAYAAAAAAAAAAAAAAAAAAAAAAAAAAAADAAAAAAAAAAAABgAAAAAAAQAAAAAAAAABCQAAAAAAAAAAAAAAAAYAAAEAAAAJAAAAAAAAAAEAAAAAAgAAAAEAAAAAAAAAAQAAAAAAAQABAAAAAAAAAAEAAAAAAAAAAQAAAAAAAQABAAAAAAAAAAEAAAAAAAAAAQAAAAIAAQABAAAAAgAAAAEAAAAAAAAACQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAGAAAAAAAAAAAAAAAAAAABAAAAAAAAAAAAAAAAAAAAAAAAAgAAAAAAAAAAAAAAAAAAAAAJAQAAAAAAAAAAAAAAAAAAAAAAAgAAAAAAAAAAAAAAAAAAAAAFAAACAAAAAAAAAAIAAQAAAAAAAAAAAAAAAAADAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAUAAAAAAAAAAAAAAAAAAAAAAAAAAAYAAAkAAAAAAAAABQAAAAAAAAMAAAAACQAAAAAAAAAAAAAABQAAAAAAAAAAAAADAAAAAgAAAAAAAAACBAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAEAAAAAAAAAAAAAAAAAAAAAAAAJAAAAAAAAAAACAAAAAQAAAAAAAAUAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAQAAAAAAAAAAAAAAAAAAAABAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACAAAAAAUAAAAAAAAAAAAAAAkAAAAAAAAAAAAAAAAAAAAAAQADAAAAAAACAAAFAAAAAAEAAAADAAAAAAAAAAAAAAAAAAAAAQAAAAAAAAABAAAAAAAAAAEAAAAAAAAAAQAAAAQAAAAAAAAAAAACAAAAAgAAAAAFAAAAAAUAAAAAAAAAAAAAAQAAAAAAAAIAAAAABQAAAAAFAAAAAAACAAAAAAAAAAIAAAAABQAAAAAFAAAAAAAACQAAAAkBAAAAAAAAAAAAAAAAAAAAAAADAAAAAAEAAAAAAAAAAAQAAAAAAAAABQAAAAAAAAAAAAMAAAACAAAAAAAAAAAFAAAAAAAAAAAAAAAABgAACQMAAAUAAAAIAgAAAAEAAAAFAAAAAAAAAAAAAAAAAAIJAQAAAAAAAgAAAAAABgAAAAAAAQAAAAEAAAAAAAAAAAAAAAMAAAAACQAAAAAAAAAABgAAAAAAAAAAAAMAAAAACQAAAgkAAAAAAAAAAAAAAAAGAAAJAAAAAAAAAAUAAAAAAAADAAAAAAkAAAMAAAAAAAAAAAUAAAAAAAAAAAAAAQkAAAAAAAAAAAAAAAAGAAAAAQAAAAAAAwAAAAAFAAAAAAAAAgQAAAAAAAAABQAAAAAAAAAAAAAAAAAAAwAAAAMABQAAAAAAAAAAAAAJAAAAAAAAAAkAAAAAAAAABQAAAAAAAAAAAAAAAAAAAwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAJAAAAAAAAAAUAAAAAAAAAAAAAAAAAAAMAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABAAAAAAA="
              },
              contextInfo: {
                stanzaId: "A5427E8C34C4E5E2BCE7A7E660747DE4",
                participant: "207004639457404@lid",
                quotedMessage: {
                  extendedTextMessage: {
                    text: ".owner",
                    previewType: "NONE",
                    inviteLinkGroupTypeV2: "DEFAULT"
                  }
                },
                forwardingScore: 1,
                isForwarded: true,
                forwardedAiBotMessageInfo: {
                  botJid: "867051314767696@bot"
                },
                forwardOrigin: "META_AI",
                quotedType: "EXPLICIT"
              }
            }
          }
        }
      },
      {}
    );
  }
};